name: Email Responder

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  check_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install smtplib imaplib email

    - name: Run email responder script
      run: python email_responder.py  # Make sure this matches the name of your Python script
      env:
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
