name: Send Emails with Brevo API

# Controls when the workflow will run
on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

# The type of runner that the job will run on
jobs:
  send_emails:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Python dependencies (Brevo SDK)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sib-api-v3-sdk

      # Step 4: Run the Python script to send emails
      - name: Run email sender script
        run: |
          python send_email.py

