name: Send Emails with Brevo API

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute for testing

jobs:
  send_emails:
    runs-on: ubuntu-latest
    steps:
    - name: Set up job
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sib-api-v3-sdk
        pip install requests

    - name: Run email sender script
      run: python send_email.py
