name: Send Emails

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual triggering

jobs:
  send_emails_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 1: Restore sent_emails.json if it exists
    - name: Restore sent emails cache
      id: cache-sent-emails
      uses: actions/cache@v3
      with:
        path: sent_emails.json
        key: sent-emails-cache
        restore-keys: sent-emails-cache

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sib-api-v3-sdk requests

    - name: Run send_email script
      run: python send_email.py

    # Step 2: Cache sent_emails.json after running the script
    - name: Update sent emails cache
      uses: actions/cache@v3
      with:
        path: sent_emails.json
        key: sent-emails-cache
        enableCrossOsArchive: true
