name: Send Emails

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  send_emails_job:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 10

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sib-api-v3-sdk requests

    # Step 4: Run the email-sending script
    - name: Run send_email script
      env:
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: python send_email.py

    # Step 5: Enable Debugging
    - name: Enable Debugging
      run: |
        echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
        echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
