name: Email Responder

on:
  schedule:
    # This is an example for running the workflow every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # This adds the manual trigger

jobs:
  check_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run email responder script
      run: |
        python your_email_responder_script.py
